### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by peterdfields** [lpryszcz/pyScaf#4]
Hi,

I'm trying to run the example commands and getting the following error:

```
./pyScaf.py -f test/contigs.reduced.fa -r test/ref.fa -o test/contigs.reduced.ref.fa
Options: Namespace(dotplot='png', fasta='test/contigs.reduced.fa', fastq=None, identity=0.33, joins=5, linkratio=0.7, load=0.2, log=<open file '<stderr>', mode 'w' at 0x7fbd138771e0>, longreads=None, mapq=10, maxgap=0, nofilter_overlaps=False, norearrangements=False, output=<open file 'test/contigs.reduced.ref.fa', mode 'w' at 0x259b4b0>, overlap=0.66, ref='test/ref.fa', threads=4)
 maxgap cut-off of 10000 bp

##################################################
[Tue Jan  9 16:18:31 2018][    9 Mb] Aligning contigs on reference...

##################################################
[Tue Jan  9 16:18:31 2018][    9 Mb] Saving dotplots to: test/contigs.reduced.fa.png
Traceback (most recent call last):
  File "./pyScaf.py", line 1294, in <module>
    main()
  File "./pyScaf.py", line 1286, in main
    s.save(out)
  File "./pyScaf.py", line 171, in save
    self._get_scaffolds()
  File "./pyScaf.py", line 1094, in _get_scaffolds
    t2hits, t2size = self._get_hits()
  File "./pyScaf.py", line 1035, in _get_hits
    dotplot = self.save_dotplot(self.genome, readstdin=True)
  File "./pyScaf.py", line 212, in save_dotplot
    proc = subprocess.Popen(args, stdin=subprocess.PIPE, stderr=self.log)
  File "/home/peter/.pyenv/versions/2.7.6/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/home/peter/.pyenv/versions/2.7.6/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
It doesn't seem to matter whether I build the software from github or use pip/bioconda for installation. 

The computer is running Ubuntu 16.04 and python 2.7.6

**Comment by lpryszcz** [comment]
Can you make sure the LAST-aligner (lastal) is correctly installed in your system?

**Comment by peterdfields** [comment]
It appears to be. I get the following output when executing lastal on the terminal:

```
lastal: please give me a database name and sequence file(s)

Usage: lastal [options] lastdb-name fasta-sequence-file(s)
```

**Comment by lpryszcz** [comment]
can you list test dir `ls -lah test/`?

**Comment by SilviaHinojosa1983** [comment]
Hi 
I've got the same error. I did ls -lah test/ and I got this:
otal 2,8M
drwxr-xr-x 2 shinojosa molevol 4,0K jul 12 12:24 .
drwxr-xr-x 7 shinojosa molevol 4,0K jul 12 12:39 ..
-rw-r--r-- 1 shinojosa molevol 173K jul 12 12:24 contigs.fa
-rw-r--r-- 1 shinojosa molevol  98K jul 12 12:24 contigs.reduced.fa
-rw-r--r-- 1 shinojosa molevol 622K jul 12 12:24 nanopore.fa.gz
-rw-r--r-- 1 shinojosa molevol 1,8M jul 12 12:24 pacbio.fq.gz
-rw-r--r-- 1 shinojosa molevol 100K jul 12 12:24 ref.fa
